### ISSUE TITLE
New endpoint to return whole week

### ISSUE THREAD

**Issue by Alex-Felten** [aprimautd18/UTDesignSpring18#18]
Given a date, return the whole week from Sunday - Saturday, regardless of if the date provided is the first day of the week. The returned array needs to contain the original date.

**Comment by ffejhog** [comment]
Already implemented. https://seniordesign2018dev.azurewebsites.net/swagger/#!/Calendar/ApiCalendarWeekLookupGet

/api/Calendar/weekLookup
